### ISSUE TITLE
Customer object is null when built with all the data passed correctly

### ISSUE THREAD

**Issue by usmanabid94** [PayHereLK/payhere-mobilesdk-ios#18]
i am getting customer object nill here is the code block:
let  initRequest:InitRequest = InitRequest()
        initRequest.merchantId = merchantID
        initRequest.merchantSecret = "yutfgjbhkjniohuiy"
        initRequest.customer?.firstName = "Pay"
        initRequest.customer?.lastName = "Here"
        initRequest.customer?.email = "test@test.com"
        initRequest.customer?.phone = "+9477123456"
        initRequest.customer?.deliveryAddress?.city = "Colombo"
        initRequest.customer?.deliveryAddress?.country = "Sri Lanka"
        initRequest.orderId = "001"
        initRequest.itemsDescription = "PayHere SDK Sample"
        initRequest.items = [item1,item2]
        initRequest.currency = "LKR"
        initRequest.amount = 50.00
        initRequest.customer?.deliveryAddress?.city = "hgfgchgv"
        initRequest.customer?.deliveryAddress?.country = "kbgfrytuykh"
        initRequest.custom1 = "custom 01"
        initRequest.custom2 = "custom 02"
        
            let phVC = PHViewController()
              phVC.initRequest = initRequest
              phVC.delegate = self
              phVC.isSandBoxEnabled = true
              phVC.modalPresentationStyle = .overCurrentContext
      
              self.present(phVC, animated: true, completion: nil)

**Comment by usmanabid94** [comment]
@Thisura98  @kamalsampathupsena @kamalupasena

**Comment by PayHereDevs** [comment]
@usmanabid94  Please follow the bellow implementation
```
let merchantID = ""
let item = Item(id: "item_1", name: "Item 1", quantity: 1, amount: 50.0)
let initRequest = PHInitialRequest(
    merchantID: merchantID, 
    notifyURL: "", 
    firstName: "Pay", 
    lastName: "Here", 
    email: "test@test.com", 
    phone: "+9477123456", 
    address: "Colombo", 
    city: "Colombo", 
    country: "Sri Lanka", 
    orderID: "001", 
    itemsDescription: "PayHere SDK Sample", 
    itemsMap: [item], 
    currency: .LKR, 
    amount: 50.00,
    deliveryAddress: "", 
    deliveryCity: "", 
    deliveryCountry: "", 
    custom1: "custom 01", 
    custom2: "custom 02"
) 
```
User `PHInitialRequest` instead of `InitRequest`

**Comment by usmanabid94** [comment]
@PayHereDevs 
I have tried to use the implementation you shared but still i am getting this error:
Cannot find 'PHInitialRequest' in scope
Here is what my pod file looks like.Let me know if there is any pod file installation i am missing:
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target ‘Myproject’ do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Myproject
    pod 'payHereSDK'
    #Facebook login
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    
    #Google Login With Firebase
    pod 'GoogleSignIn'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'GoogleAnalytics'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    # IQKeyboardManager
    pod 'IQKeyboardManagerSwift'
    
    #Activity Indicator View
    pod 'NVActivityIndicatorView'
    
    #For Side Menu
    pod 'SlideMenuControllerSwift'
    
    #Network
    pod 'Alamofire'
    
    #Bar Button View
    pod 'XLPagerTabStrip', '~> 8.1'
    
    # Star control
    pod 'Cosmos'
    
    #TextField Effects
    pod "TextFieldEffects"
    
    # DropDown Menu
    pod 'DropDown'
    
    #Device Identification
    pod 'DeviceKit'
    
    #For Search Places
    pod 'GooglePlaces'
    pod 'GooglePlacePicker' 
    pod 'GoogleMaps'    
    
    #Image Cache
    pod 'SDWebImage'
    
    #Youtube Video Player
    #pod 'YouTubePlayer'
    
    #For Image Sliding
    pod 'ImageSlideshow'
    pod "ImageSlideshow/Alamofire"
    
    #Rich Text Editor
    #pod "RichEditorView"
    
    #Gallery Image Picker
    pod 'OpalImagePicker'
    
    #ProgressBar
    pod 'RangeSeekSlider'
    
    #AdMob
    pod 'Google-Mobile-Ads-SDK'
    #pod 'PersonalizedAdConsent'
    
    #In App Purchases
    pod 'SwiftyStoreKit'
    
    #Textfield Shake
    pod 'UITextField+Shake'
    
    #Push Notification
    pod 'NotificationBannerSwift'
    
    #Show Action Sheet
    pod 'ActionSheetPicker-3.0'
    
    #Picker Library
    # pod 'TCPickerView'
    
    #Message Kit
    # pod 'MessageKit'
    # pod 'MessageInputBar'
    #pod 'JSQMessagesViewController', '7.3.3'
    
    pod 'SwiftCheckboxDialog'
    pod 'JGProgressHUD'

    #Play Gif 
    pod 'SwiftyGif'
    pod 'Popover'
    
    
    pod 'MapboxGeocoder.swift', '~> 0.11'
    #pod 'Mapbox-iOS-SDK', '~> 5.4'
    pod 'Alamofire-SwiftyJSON'
     
    #Intro App
    pod 'OnboardKit'
     #pod 'LinkedinSwift'
#pod 'LinkedinSwift', '>= 1.7.9'

pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
pod 'SOTabBar'
pod 'FSPagerView'
#pod 'FanMenu'
pod "ZGTooltipView"
pod 'CollageView', '~> 1.0.4'
    #Socket
    pod 'Socket.IO-Client-Swift', '~> 15.2.0'
    #progressBar
    pod 'MaterialProgressBar'
    #SLiderImages
pod "ZoomableImageSlider"
  #carousel
#pod "CLabsImageSlider", '~> 0.1.2'
#pod 'ZCycleView'


end

**Comment by usmanabid94** [comment]
@PayHereDevs When i tried to use it in a new project i am getting this error:
Error Domain= Code=501 "Unauthorized domain"
when executing the build.

**Comment by PayHereDevs** [comment]
@usmanabid94 you need to add your package details from the payhere dashboard 

Go to Side Menu > Integrations section of your PayHere Account
Click 'Add Domain/App' > Enter your top level domain or App package name > Click 'Request to Allow'
Wait for the approval for your domain/app (This will take up to 24 hours)
Copy the Merchant Secret shown in front of your domain/app

**Comment by usmanabid94** [comment]
> @usmanabid94 you need to add your package details from the payhere dashboard
> 
> Go to Side Menu > Integrations section of your PayHere Account Click 'Add Domain/App' > Enter your top level domain or App package name > Click 'Request to Allow' Wait for the approval for your domain/app (This will take up to 24 hours) Copy the Merchant Secret shown in front of your domain/app

@PayHereDevs It worked for me now Thanks alot.
