### ISSUE TITLE
Example application

### ISSUE THREAD

**Issue by nirojan0930** [PayHereLK/payhere-mobilesdk-ios#4]
Hi, Im struggle to present the phViewController on top of my view. Can you provide any example application to get better understanding?

**Comment by nirojan0930** [comment]
let phVC = PHViewController()
phVC.initRequest = req
phVC.delegate = self
phVC.isSandBoxEnabled = true  
phVC.modalPresentationStyle = .overCurrentContext

self.present(phVC, animated: true, completion: nil)

let req : InitRequest = InitRequest()
req.merchantId = "1210251"      // Your Merchant ID
req.merchantSecret = "bhasha2"  // Your Merchant secret
req.amount = 100.0              // Amount which the customer should pay
req.currency = "LKR"            // Currency
req.orderId = "ABCDWXYZ"        // Unique ID for your payment transaction
req.itemsDescription = "1 Greeting Card"    // Item title or Order/Invoice number
req.custom1 = "This is the custom 1 message"
req.custom2 = "This is the custom 2 message"
.......................................

When i run the project using like above it's says req is not defined.

**Comment by Thisura98** [comment]
@nirojan0930 I looked at the sample code you provided and it seems that you are referencing the `req` variable before the line where it is defined.

I modified your code. Try it and let me know if it works for you.

```
let req : InitRequest = InitRequest()
req.merchantId = "1210251" // Your Merchant ID
req.merchantSecret = "bhasha2" // Your Merchant secret
req.amount = 100.0 // Amount which the customer should pay
req.currency = "LKR" // Currency
req.orderId = "ABCDWXYZ" // Unique ID for your payment transaction
req.itemsDescription = "1 Greeting Card" // Item title or Order/Invoice number
req.custom1 = "This is the custom 1 message"
req.custom2 = "This is the custom 2 message"

// Moved the PHViewController definition and
// present methods below the definition of the
// req variable.

let phVC = PHViewController()
phVC.initRequest = req
phVC.delegate = self
phVC.isSandBoxEnabled = true
phVC.modalPresentationStyle = .overCurrentContext

self.present(phVC, animated: true, completion: nil)
```

**Comment by usmanabid94** [comment]
i am getting customer object nill here is the code block:
let  initRequest:InitRequest = InitRequest()
        initRequest.merchantId = merchantID
        initRequest.merchantSecret = "yutfgjbhkjniohuiy"
        initRequest.customer?.firstName = "Pay"
        initRequest.customer?.lastName = "Here"
        initRequest.customer?.email = "test@test.com"
        initRequest.customer?.phone = "+9477123456"
        initRequest.customer?.deliveryAddress?.city = "Colombo"
        initRequest.customer?.deliveryAddress?.country = "Sri Lanka"
        initRequest.orderId = "001"
        initRequest.itemsDescription = "PayHere SDK Sample"
        initRequest.items = [item1,item2]
        initRequest.currency = "LKR"
        initRequest.amount = 50.00
        initRequest.customer?.deliveryAddress?.city = "hgfgchgv"
        initRequest.customer?.deliveryAddress?.country = "kbgfrytuykh"
        initRequest.custom1 = "custom 01"
        initRequest.custom2 = "custom 02"
        
            let phVC = PHViewController()
              phVC.initRequest = initRequest
              phVC.delegate = self
              phVC.isSandBoxEnabled = true
              phVC.modalPresentationStyle = .overCurrentContext
      
              self.present(phVC, animated: true, completion: nil)
